server:
  port: 8088

keycloak-client:
  server-url: http://iam.uengine.io:8080/auth
  realm: uEngine5-bpm

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: definition-service
          uri: http://definition-service:9093
          predicates:
            - Path=/definition/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: create-app
          uri: http://definition-service:9093
          predicates:
            - Path=/create-app/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: version
          uri: http://definition-service:9093
          predicates:
            - Path=/version/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: instance
          uri: http://process-service:9094
          predicates:
            - Path=/instance/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: instance-entity
          uri: http://process-service:9094
          predicates:
            - Path=/instances/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: instance-service
          uri: http://process-service:9094
          predicates:
            - Path=/services/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: instance-service-definitions
          uri: http://process-service:9094
          predicates:
            - Path=/service-definitions/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: worklist-entity
          uri: http://process-service:9094
          predicates:
            - Path=/worklist/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: instance-workitem
          uri: http://process-service:9094
          predicates:
            - Path=/work-item/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: metadata
          uri: http://process-service:9094
          predicates:
            - Path=/classdefinition/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: bpm
          uri: http://process-service:9094
          predicates:
            - Path=/bpm/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: login-handler
          uri: http://login-handler:9091
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: backoffice-frontend
          uri: http://back-office:8082
          predicates:
            - Path=/admin/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin/(?<path>.*),/$\{path}
        - id: workspace
          uri: http://workspace:8083
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://iam.uengine.io:8080/auth/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: uEngine5-bpm
            client-secret: 3fb17176-33e7-47bb-b66f-e17505ba5ebe
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: http://iam.uengine.io:8080/auth/realms/${keycloak-client.realm}/protocol/openid-connect/certs
