apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: definition-service
  name: definition-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: definition-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: definition-service
    spec:
      containers:
      - image: gcr.io/eventstorming-tool/uengine5-bpm-definition-service:latest
        imagePullPolicy: IfNotPresent
        name: definition-service
        ports:
        - containerPort: 9093
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
