apiVersion: v1
kind: Service
metadata:
  labels:
    run: definition-service
  name: definition-service
spec:
  ports:
  - port: 9093
    protocol: TCP
  selector:
    run: definition-service
  type: ClusterIP

# apiVersion: "v1"
# kind: "Service"
# metadata:
#   labels:
#     run: definition-service
#   name: definition-service
# spec:
#   ports:
#   - port: 8080
#     protocol: TCP
#   selector:
#     run: definition-service
#   type: ClusterIP