# spring:
#   profiles: default
#   cloud:
#     stream:
#       kafka:
#         binder:
#           brokers: uengine-kafka:9092  # ${vcap.services.kakfa.host_port} and inject value from env variable
#           zkNodes: uengine-zookeeper:2181
#       bindings:
#         bpm-topic:
#           destination: bpm.topic
#           contentType: application/json

# eureka:
#   client:
#     enabled: false

# server:
#   port: 9094
#   servletPath: /
# #  ssl:
# #    key-store: src/test/resources/keystore.p12
# #    key-store-password: mypassword
# #    keyStoreType: PKCS12
# #    keyAlias: uengine
# ---
# spring:
#   cloud:
#     stream:
#       kafka:
#         binder:
#           brokers: my-kafka.kafka.svc.cluster.local:9092
#         streams:
#           binder:
#             configuration:
#               default:
#                 key:
#                   serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                 value:
#                   serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#       bindings:
#         event-in:
#           group: process
#           destination: bpm.topic
#           contentType: application/json
#         event-out:
#           destination: bpm.topic
#           contentType: application/json
server:
  port: 9094

eureka:
  client:
    enabled: false

spring:
  # profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
          zkNodes: my-kafka-zookeeper.kafka.svc.cluster.local:2181
      bindings:
        bpm-topic:
          destination: bpm.topic
          contentType: application/json
